services:
  backend:
    build:
      context: .
      dockerfile: api/Dockerfile
      target: backend
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
